# Generated by Django 4.0.3 on 2022-07-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='arquivo',
            field=models.FileField(default=0, upload_to='Uploaded Files/'),
            preserve_default=False,
        ),
    ]
