# Generated by Django 4.0.3 on 2022-08-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='teste',
            field=models.FileField(default=0, upload_to='', verbose_name=(' Morbidade Hospitalar do SUS - por local de residência - Brasil',)),
            preserve_default=False,
        ),
    ]
