# Generated by Django 4.0.3 on 2022-08-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tabela_delete_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tabela',
        ),
    ]
